language: c

before_install:
    test -n $CC && unset CC

before_script:
    - make env_prepare
    - sudo ln -sf toolchain/bin/* /usr/bin/
    - . ./env.sh;
    - "curl -s https://sourcery.mentor.com/public/gnu_toolchain/arm-none-eabi/arm-2014.05-28-arm-none-eabi-i686-pc-linux-gnu.tar.bz2 | sudo tar xjf - -C /opt && export RTT_EXEC_PATH=/opt/arm-2014.05/bin && /opt/arm-2014.05/bin/arm-none-eabi-gcc --version || true"
script:
    - scons -C src

